### ISSUE TITLE
missing pkg "lcmtypes_pronto-lcmtypes" for pronto_translators

### ISSUE THREAD

**Issue by tony950309** [mitdrc/pronto-distro#43]
Dr Fallon:
I am using pronto for Valkyrie, when encoding translator i got such error msg:
_Package lcmtypes_pronto-lcmtypes was not found in the pkg-config search path.
Perhaps you should add the directory containing `lcmtypes_pronto-lcmtypes.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lcmtypes_pronto-lcmtypes' found
CMake Error at pronto_translators/cmake/pods.cmake:257 (string):_

actually I didn't find ~/pronto-distro/build/lib64/ ,I think the folder and all the related hpp files are missing.
or do I need any modification on my PC.
The contents I add to bashrc is :  ( /jg is my account name)
_export PATH=/home/jg/pronto-distro/build/bin:$PATH 
source /opt/ros/indigo/setup.bash 
export PKG_CONFIG_PATH=/home/jg/pronto-distro/build/lib/pkgconfig/:/home/jg/pronto-distro/build/lib64/pkgconfig/:$PKG_CONFIG_PATH 
export LD_LIBRARY_PATH=/home/jg/pronto-distro/build/lib/:/home/jg/pronto-distro/build/lib64/:$LD_LIBRARY_PATH 
export DRC_BASE=/home/jg/pronto-distro_

Any help would be appreciated.

**Comment by crankler** [comment]
@tony950309 
So have you solve this problem? Or can you give me some advices on how to solve this issue?Thank you!

**Comment by mauricefallon** [comment]
Note: we are no longer supporting this distribution.
We have shifted away from using LCM
