### ISSUE TITLE
Compile error on fresh checkout of pronto-distro (Ubuntu 14.04/64Bit)

### ISSUE THREAD

**Issue by skohlbr** [mitdrc/pronto-distro#5]
This happens to me when following the install instructions and running "make":
<pre>
[ 88%] Built target test-point-cloud-pcl
Scanning dependencies of target pronto-multisense-to-frame
[100%] Building CXX object src/tools/CMakeFiles/pronto-multisense-to-frame.dir/pronto_multisense_to_frame.cpp.o
/home/kohlbrecher/tmp/pronto_crash_test/pronto/pronto-utils/src/tools/pronto_multisense_to_frame.cpp:10:42: fatal error: lcmtypes/drc/atlas_state_t.hpp: No such file or directory
 #include <lcmtypes/drc/atlas_state_t.hpp>
                                          ^
compilation terminated.
make[5]: *** [src/tools/CMakeFiles/pronto-multisense-to-frame.dir/pronto_multisense_to_frame.cpp.o] Error 1
make[4]: *** [src/tools/CMakeFiles/pronto-multisense-to-frame.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
</pre>
Any ideas what the cause might be are appreciated.

**Comment by skohlbr** [comment]
I managed to "fix" compilation by removing the CMakeLists.txt from the "pronto-utils/src/tools" folder, but that clearly is not the correct solution :)

**Comment by mauricefallon** [comment]
I fixed this one a few weeks back in 'pronto' but i need to update the tag in 'pronto-distro'
I'm working on testing pronto with an atlas v4 log, and then I'll update that tag today.
