### ISSUE TITLE
Updated Multisense Calibration scheme

### ISSUE THREAD

**Issue by swhart115** [mitdrc/pronto-distro#7]
I noticed in the ros2lcm translator node that the multisense calibration parameters sent over LCM to MULTISENSE_STATE is written in terms of the "old" driver way of doing things (i.e., individual joint cal vals), whereas the latest driver collapses those into a single calibration transform, most easily accessible via \tf.  

Is there any plan to update the pronto side of things here to bring this up to date? and if not, where is the appropriate place to make the change on the pronto side, if i wanted to do it myself?

**Comment by swhart115** [comment]
of course, it doesnt look like the translator node is doing anythign then setting the names of these "cal" joints, so maybe this doesnt matter.  just want to make sure though.

**Comment by mauricefallon** [comment]
Yes, this has now been upgraded. I no longer use the old cal joints.

In fact they were never really used in our system and we just filled them in with zeros.
